In [1]:
import sys
sys.path.append("..")

from services.segments_database import do_query, insert_trainingdata_from_chapter
import pandas as pd

In [4]:
current_category = 'zk'
zk_category_id = 4

In [13]:
results = []
query = '''
  SELECT *
  FROM chapter
  ORDER BY RAND()
  LIMIT {};
'''

res = do_query(query.format(10))
df = pd.DataFrame(res.fetchall())
df.columns = res.keys()
results.append(df)
    
df = pd.concat(results, ignore_index=True)
df.shape

(10, 21)

In [14]:
df.head()

,id,text,chapter_idx,chapter_number,header,header_preprocessed,parent_header,parent_preprocessed,grandparent_header,grandparent_preprocessed,...,topic_1_value,topic_2_id,topic_2_value,topic_3_id,topic_3_value,topic_4_id,topic_4_value,topic_5_id,topic_5_value,document_id
0,196702,\n221\n,10,None,220\n,220,,,,,...,0.001361,15.0,0.001178,5.0,0.000479,21.0,0.000444,12.0,0.000199,8059
1,283439,\n.1\tNach der Auftragserteilung erarbeiten di...,7,1.4.2,Detailkonzeption\n,detailkonzeption,Leistungen\n,leistung,Ausschreibung\n,ausschreibung,...,0.019353,39.0,0.017896,0.0,0.005668,6.0,0.003783,13.0,0.003687,6649
2,140456,\nBaugrubenaushub maschinell\n\nR\t900\tDer Et...,48,None,300\tAushubarbeiten Betreffend Vergütungsregel...,300 aushubarbeit betreffend vergütungsregelung...,,,,,...,0.049574,33.0,0.008901,18.0,0.003870,37.0,0.002154,10.0,0.001322,8065
3,149262,\nSämtliche aus dem Mandat entstehenden Berich...,15,None,Adressat\n,adressat,,,,,...,0.003458,17.0,0.000901,39.0,0.000416,4.0,0.000375,13.0,0.000053,6650
4,190648,,10,5.1,Bemerkungen\t:\n,bemerkung,Anzahl Mitarbeiter und Funktionen\n,anzahl mitarbeiter funktion,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1085

In [15]:
for i, d in df.iterrows():
    print('inserting trainingdata {0} of {1}'.format(i, len(df)))
    try:
        insert_trainingdata_from_chapter(
            d,
            current_category,
            950,
            d['topic_1_id'] == zk_category_id
        )
    except: 
        print(sys.exc_info())

inserting trainingdata 0 of 10
inserting trainingdata 1 of 10
inserting trainingdata 2 of 10
inserting trainingdata 3 of 10
inserting trainingdata 4 of 10
(<class 'sqlalchemy.exc.ProgrammingError'>, ProgrammingError('(MySQLdb._exceptions.ProgrammingError) nan can not be used with MySQL'), <traceback object at 0x000002300C29BFC8>)
inserting trainingdata 5 of 10
inserting trainingdata 6 of 10
inserting trainingdata 7 of 10
inserting trainingdata 8 of 10
inserting trainingdata 9 of 10